/**
 * TermsConditionsScreen — Replicates the IITPK AI Faculty terms & conditions page pixel-perfect.
 */

import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  StatusBar,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { useTheme } from '../../store/ThemeContext';
import { moderateScale, scale, verticalScale } from '../../utils';

const SECTIONS = [
  {
    title: 'Parties',
    content: 'This Agreement is between VSynergize Outsourcing Pvt. Ltd. ("VSynergize," "we," "our," or "us") and the user ("Customer," "you," or "your").',
  },
  {
    title: 'Use of the Service',
    content: 'By signing up for AIFaculty.ai, you authorize VSynergize to enable a Voice AI agent on your website, mobile version etc.\nYou grant permission for VSynergize to crawl, analyze, and use data from your website to train and improve the AI agent.',
  },
  {
    title: 'Permitted Use & Responsibilities',
    content: 'You agree to provide accurate, current, and complete information.\nYou are responsible for ensuring your website content complies with applicable laws and regulations.\nYou warrant that you have the necessary rights and permissions to allow VSynergize to access, analyze, and use your website content for training purposes.',
  },
  {
    title: 'Intellectual Property Rights',
    content: 'You retain ownership of your website content.\nAll intellectual property rights related to the AI models, training data, and the AI agent, including improvements and derivatives thereof, remain the exclusive property of VSynergize.\nYou agree not to reverse engineer, recreate, modify, or attempt to extract the source code or underlying algorithms of the AI models or services.',
  },
  {
    title: 'Data, Privacy, and Sharing',
    content: 'Your data will be processed, stored, and shared with third-party cloud service providers, Large Language Models (LLMs), and other service providers necessary for delivering and improving the AI services.\nBy agreeing to these terms, you acknowledge and consent that your data may be transmitted to and stored by third-party providers, located within or outside your country.\nYou agree that your data may be used to train and improve our AI models.\nWe will employ reasonable security measures to protect your data but are not responsible for breaches beyond our control.',
  },
  {
    title: 'Training and Customization',
    content: 'You consent to VSynergize training the AI agent using data collected from your website and interactions.\nYou understand that improvements and retraining may lead to changes in the AI\'s responses over time.',
  },
  {
    title: 'Indemnity & Limitation of Legal Actions',
    content: 'You agree to indemnify and hold harmless VSynergize, its affiliates, officers, and employees from any claims, damages, liabilities, costs, or expenses arising from your breach of this Agreement or misuse of the services.\nYou agree not to sue or pursue any legal claims against VSynergize related to the AI\'s responses, including but not limited to inaccuracies, wrong answers, or any damages resulting from use of the AI.\nVSynergize shall not be responsible or liable for any incorrect, misleading, or inappropriate responses generated by the LLMs or AI models.',
  },
  {
    title: 'Limitation of Liability',
    content: 'To the maximum extent permitted by law, VSynergize shall not be liable for any damages, direct or indirect, arising out of or related to your use or inability to use the service, including damages caused by incorrect responses from AI models.\nOur total liability shall not exceed the fees paid by you for the last 3 months, if any, for the services.',
  },
  {
    title: 'Ownership & Restrictions',
    content: 'All intellectual property rights in the AI models, underlying code, and derivatives remain with VSynergize.\nYou shall not, directly or indirectly, reverse engineer, decompile, disassemble, recreate, copy, modify, or attempt to derive source code or algorithms related to VSynergize\'s proprietary services.',
  },
  {
    title: 'User Data & Third-Party Service Providers',
    content: 'Your data will be transmitted to, stored by, and processed through third-party cloud service providers, LLMs, and other relevant vendors for the operation, training, and improvement of the AI agent.\nBy proceeding, you agree that VSynergize and its third-party providers have the right to handle your data as described, and you release VSynergize and these providers from any liability related to data processing and storage.',
  },
  {
    title: 'Changes to the Terms',
    content: 'VSynergize may update these Terms and Conditions from time to time. Continued use of the service after changes indicates your acceptance of those changes.',
  },
  {
    title: 'Consent UX Copy (Web/App + IVR)',
    content: 'Recording/Processing Consent (modal on first use):\nAIFaculty.ai will record your voice and send the audio/text to our voice provider to generate speech/transcripts and respond to you. We store your audio and transcripts to power features you use. You can download or delete your data anytime in Settings → Privacy. This is optional and you can withdraw consent at any time.\n\nService delivery (required to use voice):\nI consent to AIFaculty.ai recording my voice and processing it to provide voice features.\n\nImprove the product (optional):\nI consent to AIFaculty.ai using my recordings/transcripts to improve models and quality.\n\nShare with integrated services (optional):\nI consent to AIFaculty.ai sharing transcripts/metadata with my connected tools (e.g., CRM/helpdesk) as configured by me.\n\nMarketing contact (optional):\nI consent to receive product updates or offers.\n\nOngoing banner:\n"We record your voice to respond. Manage or withdraw consent in Settings."\n\nIVR/Phone script:\n"This call may be recorded and analyzed by AI to assist you. Press 1 to consent and continue with recording. Press 2 to continue without recording."\n\nChildren/minors gate:\n"Are you 18 or older? By continuing to use the platform you declare that you are 18 years and above."',
  },
  {
    title: 'Privacy Policy',
    content: 'What we collect:\nAudio & transcripts (your spoken input and text conversions), technical metadata (timestamps, device/network info, language, error logs), optional voice artifacts (embeddings/voiceprints only if you enable voice identity features), and integration data if you connect third-party tools.\n\nWhy we collect:\nTo provide and improve voice features, generate spoken responses, maintain security, debug issues, and prevent abuse. Product improvement and marketing communications only if you opt in.\n\nYour choices:\nYou can withdraw consent at any time in Settings → Privacy, and download or delete your recordings and transcripts in Settings.\n\nSharing & processors:\nWe use vetted service providers to process voice and host data. The current list of sub-processors is available on our website. We require each provider to implement appropriate security and only process data under our written instructions.\n\nRetention:\nAudio and transcripts are deleted after 180 days by default (configurable in your account). Voice embeddings/voiceprints (if enabled) are deleted upon request or after last use. We minimize retention and never keep data longer than necessary.\n\nInternational transfers:\nWe may process data in or transfer it to regions where we or our processors operate. Where required, we use Standard Contractual Clauses (SCCs) or equivalent safeguards.\n\nSecurity:\nWe apply encryption in transit and at rest, access controls (least privilege), audit logging, and routine security testing.\n\nChildren:\nAIFaculty.ai is not directed to children. We do not knowingly collect voice data from minors without verifiable parental consent.\n\nContact / DPO:\nData Protection Officer: Nazim Maulvi · nazim.m@vsynergize.com · VSynergize Outsourcing Pvt Ltd, IT 6 Building, Qubix Business Park, Hinjewadi, Pune 411057.',
  },
  {
    title: 'Terms of Use Clauses',
    content: 'User responsibilities & lawful recording:\nYou must have all necessary rights and consents to record and upload audio. You will not record others or upload content that infringes rights, violates law, or breaches confidentiality.\n\nNo unauthorized impersonation / voice cloning:\nYou may not clone or simulate any person\'s voice without their express written consent. If you share AI-generated audio, you must clearly label it as synthetic.\n\nAI outputs:\nOutputs may be inaccurate. They are provided "as is" and are not medical, legal, financial, or other professional advice.\n\nRate limits & misuse:\nWe may throttle or suspend accounts for abuse, evasion, or regulatory risk (e.g., deceptive robocalls, political manipulation, harassment).\n\nData use:\nBy default we do not use your recordings to train models unless you enable that setting. You grant AIFaculty.ai a limited license to process content solely to provide the services you select.\n\nTelephony compliance:\nIf you use outbound calls or messages, you must obtain all legally required consents (e.g., TCPA in the U.S., TRAI TCCCPR in India). You agree to honor DNC/DND rules and maintain auditable consent records.\n\nLiability cap:\nTo the maximum extent permitted by law, our aggregate liability is capped at the fees paid in the preceding 3 months.',
  },
  {
    title: 'Vendor DPA Rider',
    content: 'Purpose & role:\nVSynergize acts as Controller (or Processor on behalf of enterprise customers); voice service vendors act as Processor/Sub-processor solely to deliver voice generation/transcription.\n\nInstructions:\nVendors will process Personal Data only per VSynergize\'s documented instructions; no sale of Personal Data.\n\nConfidentiality & security:\nVendors ensure personnel confidentiality, implement security appropriate to risk (encryption, access control, logging, incident response), and support security reviews and audits.\n\nData minimization & retention:\nDefault retention for audio and transcripts is 180 days or shorter as configured; upon instruction, vendors will delete or return Personal Data and certify deletion.\n\nSub-processors:\nVendors will maintain a sub-processor list and provide notice of material changes; VSynergize may object on reasonable grounds.\n\nInternational transfers:\nFor transfers from the EEA/UK/Switzerland, Standard Contractual Clauses (SCCs) and any UK Addendum apply. Supplementary measures will be implemented if required.\n\nBreach notification:\nVendors will notify VSynergize without undue delay after becoming aware of a Personal Data Breach, sharing relevant details and mitigation steps.',
  },
  {
    title: 'Telephony Consent Lines',
    content: 'Website form (U.S. TCPA-ready):\n"By submitting, you agree AIFaculty.ai may contact you at the number provided using automated technology and/or prerecorded/artificial voice for service and marketing. Consent is not a condition of purchase. You can opt out anytime."\n\nIndia (TRAI TCCCPR prompt):\n"By submitting, you consent to receive service and promotional calls/SMS from AIFaculty.ai on your registered number, and confirm your DND preferences allow such messages. You can opt out anytime."',
  },
  {
    title: 'Record-Keeping & Controls',
    content: 'Sub-processor register lists all vendors and regions used.\nAccount-level training is OFF by default; screenshot setting available for audit.\nRetention set to 180 days; automatic deletion job verified.\nAccess to raw audio restricted to least-privilege roles; all accesses logged.\nConsent ledger records: user ID, IP, timestamp, UI version, per-toggle choices, source (web/IVR).\nDeletion workflow: user self-service and admin override; vendor deletion API wired.\nLabeling: any exported synthetic audio is clearly tagged "AI-generated."\nAbuse prevention: block uploads that are obviously someone else\'s voice without proof of consent; flag celebrity/public figure cloning.\nIncident runbook: DPDP/GDPR/TCPA/TRAI notification steps with contacts.',
  },
  {
    title: 'Retention Schedule',
    content: 'Raw audio:\n180 days (default); immediate deletion if user declines storage.\n\nTranscripts & logs:\n180 days (default); extended only if user enables "Memory."\n\nVoice embeddings/voiceprints (if enabled):\nDeleted on request or after last use (maximum 6 months).\n\nBackups:\nRolling 180 days; no restoration for deleted user data except for disaster recovery.',
  },
  {
    title: 'Governing Law & Jurisdiction',
    content: 'This Agreement shall be governed by and construed in accordance with the laws of Pune, India.\nAny disputes arising out of or related to this Agreement shall be subject to the exclusive jurisdiction of courts in Pune, India.',
  },
  {
    title: 'Miscellaneous',
    content: 'No transfer of rights or obligations shall occur without prior written consent from VSynergize.\nIf any provision of this Agreement is found to be invalid or unenforceable by a court of competent jurisdiction, the remaining provisions shall remain in full force and effect.\nThis Agreement constitutes the entire understanding between you and VSynergize regarding the use of the Services and supersedes all prior agreements, whether written or oral.\nAny delay or failure by VSynergize to enforce any provision shall not be considered a waiver of those rights.\nYou acknowledge that you have read, understood, and agree to these Terms and Conditions.\n\nVSynergize Outsourcing Pvt Ltd',
  },
];

const TermsConditionsScreen: React.FC = () => {
  const { colors, isDarkMode, toggleTheme } = useTheme();
  const styles = getStyles(colors, isDarkMode);
  const navigation = useNavigation();
  const insets = useSafeAreaInsets();

  return (
    <View style={[styles.safeArea, { paddingTop: insets.top }]}>
      <View style={styles.container}>
        
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity 
            style={styles.iconBtn} 
            onPress={() => navigation.goBack()}
          >
            <Icon name="arrow-left" size={moderateScale(24)} color={colors.textPrimary} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Terms and Conditions</Text>
          <TouchableOpacity style={styles.themeToggle} onPress={toggleTheme}>
            <Icon
              name={isDarkMode ? 'weather-sunny' : 'weather-night'}
              size={moderateScale(18)}
              color={colors.textSecondary}
            />
          </TouchableOpacity>
        </View>

        {/* Content */}
        <ScrollView
          style={styles.scrollView}
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
        >
          {/* Main Title Block */}
          <View style={styles.topInfoBlock}>
            <View style={styles.titleWrapper}>
              <View style={styles.logoBox}>
                <Icon name="brain" size={moderateScale(18)} color="#FFF" />
              </View>
              <Text style={styles.mainTitle}>Terms & Conditions</Text>
            </View>
            <Text style={styles.subTitle}>VSynergize Outsourcing PVT. LTD · AIFaculty.ai</Text>
            
            <View style={styles.divider} />

            <View style={styles.introBox}>
              <Text style={styles.introText}>
                Please read these Terms and Conditions ("Agreement") carefully before signing up. By signing up, you agree to be bound by this Agreement.
              </Text>
            </View>
          </View>

          {SECTIONS.map((section, index) => (
            <View key={index} style={styles.sectionContainer}>
              <View style={styles.titleRow}>
                <View style={styles.numberBadge}>
                  <Text style={styles.sectionNumber}>{index + 1}</Text>
                </View>
                <Text style={styles.sectionTitle}>{section.title}</Text>
              </View>
              <Text style={styles.sectionContent}>{section.content}</Text>
            </View>
          ))}
          
          <View style={styles.bottomSpacer} />
        </ScrollView>

      </View>
    </View>
  );
};

/* ─── Styles ──────────────────────────────────────────────────────────── */

const getStyles = (colors: any, isDarkMode: boolean) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.backgroundWhite,
  },
  container: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  
  /* Header */
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: scale(16),
    paddingVertical: verticalScale(12),
    backgroundColor: colors.backgroundWhite,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
    elevation: isDarkMode ? 0 : 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  iconBtn: {
    padding: scale(4),
  },
  headerTitle: {
    fontSize: moderateScale(16),
    fontWeight: '600',
    color: colors.textPrimary,
  },
  themeToggle: {
    width: moderateScale(32),
    height: moderateScale(32),
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: colors.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.backgroundWhite,
  },

  /* Scroll Content */
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: scale(24),
    paddingTop: verticalScale(32),
    paddingBottom: verticalScale(40),
  },

  /* Top Info Block */
  topInfoBlock: {
    marginBottom: verticalScale(32),
  },
  titleWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(8),
  },
  logoBox: {
    width: moderateScale(32),
    height: moderateScale(32),
    borderRadius: moderateScale(8),
    backgroundColor: '#3B82F6', // Blue background
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(12),
  },
  mainTitle: {
    fontSize: moderateScale(22),
    fontWeight: '700',
    color: colors.textPrimary,
  },
  subTitle: {
    fontSize: moderateScale(14),
    fontWeight: '500',
    color: colors.textSecondary,
    marginBottom: verticalScale(20),
  },
  divider: {
    height: 1,
    backgroundColor: colors.borderLight,
    marginBottom: verticalScale(20),
  },
  introBox: {
    backgroundColor: isDarkMode ? '#1E293B' : '#F1F5F9', // Very light slate for light mode, dark for dark mode
    padding: scale(16),
    borderRadius: moderateScale(8),
    borderLeftWidth: 4,
    borderLeftColor: '#3B82F6', // Blue accent
  },
  introText: {
    fontSize: moderateScale(14),
    color: colors.textPrimary,
    lineHeight: moderateScale(22),
  },

  /* Section */
  sectionContainer: {
    marginBottom: verticalScale(28),
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: verticalScale(12),
  },
  numberBadge: {
    width: moderateScale(24),
    height: moderateScale(24),
    borderRadius: moderateScale(6),
    backgroundColor: isDarkMode ? 'rgba(59, 130, 246, 0.2)' : '#EFF6FF', // Light blue bg
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(12),
  },
  sectionNumber: {
    fontSize: moderateScale(13),
    fontWeight: '700',
    color: '#3B82F6', // Blue text
  },
  sectionTitle: {
    fontSize: moderateScale(16),
    fontWeight: '600',
    color: colors.textPrimary,
    flex: 1,
  },
  sectionContent: {
    fontSize: moderateScale(14),
    color: colors.textSecondary,
    lineHeight: moderateScale(24),
    marginTop: verticalScale(4),
  },
  
  bottomSpacer: {
    height: verticalScale(40),
  },
});

export default TermsConditionsScreen;
